.TH "HTMINL" "1" "September 2025" "htminl v0.11.0" "User Commands"
.SH NAME
HTMINL \- Manual page for htminl v0.11.0.
.SH DESCRIPTION
In\-place minification of HTML file(s).
.SS USAGE:
.TP
htminl [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while working.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version and exit.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) file and/or directory paths from this text file — or STDIN if '\-' — one entry per line, instead of or in addition to the trailing <PATH(S)>.
.SS TRAILING:
.TP
\fB<PATH(s)…>\fR
Any number of files and directories to crawl and crunch.
