.TH "HTMINL" "1" "May 2022" "HTMinL v0.6.1" "User Commands"
.SH NAME
HTMinL \- Manual page for htminl v0.6.1.
.SH DESCRIPTION
In\-place minification of HTML file(s).
.SS USAGE:
.TP
htminl [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while working.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version and exit.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) file and/or directory paths from this text file, one entry per line.
.SS <PATH(S)…>:
.TP
Any number of files and directories to crawl and crunch.
