.TH "HTMINL" "1" "February 2022" "HTMinL v0.5.7" "User Commands"
.SH NAME
HTMinL \- Manual page for htminl v0.5.7.
.SH DESCRIPTION
In\-place minification of HTML file(s).
.SS USAGE:
.TP
htminl [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while working.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.SS <PATH(S)…>:
.TP
Any number of files and directories to crawl and crunch.
